name: Demo

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  job1:
    name: data_processing_for_dataset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Process images
        run: python image_processing_script.py

      - name: Save processed data as artifact
        uses: actions/upload-artifact@v2
        with:
          name: processed_images
          path: FER-2013

  job2:
    name: data_processing_for_photo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Process images
        run: python image_processing_script_for_validation.py

      - name: Save processed photo as artifact
        uses: actions/upload-artifact@v2
        with:
          name: processed_photo
          path: photo

  model_training:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Download processed data artifact
        uses: actions/download-artifact@v2
        with:
          name: processed_images
          path: path/to/processed/data

      - name: Train model
        run: python train_model_script.py --data-path path/to/processed/data

      - name: Save trained model as artifact
        uses: actions/upload-artifact@v2
        with:
          name: trained_model
          path: path/to/trained/model

  emotion_recognition:
    needs: [model_training, job2]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Download trained model artifact
        uses: actions/download-artifact@v2
        with:
          name: trained_model
          path: path/to/trained/model

      - name: Process new images
        run: python process_images_script.py

      - name: Use trained model for emotion recognition
        run: python emotion_recognition_script.py --model-path path/to/trained/model
